version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
mcwfences = true
everycomp = true
tide = true
farmersdelight = true
mcwbyg = true
createluminous = true
overweight_farming = true
mcwwindows = true
extra_gauges = true
oceansdelight = true
ribbits = true
easymagic = true
brewinandchewin = true
chimes = true
quark = true
mcwbiomesoplenty = true
dndecor = true
easyanvils = true
createmoregirder = true
starbunclemania = true
copycats = true
stonezone = true
veggiesdelight = true
comforts = true
mcwlights = true
mcwpaths = true
ars_technica = true
create_enchantment_industry = true
immersive_furniture = true
create_sa = true
mcwtrpdoors = true
railways = true
bellsandwhistles = true
amendments = true
mynethersdelight = true
fruitsdelight = true
carpetdiem = true
moonlight = true
advancednetherite = true
biomesoplenty = true
ars_creo = true
sophisticatedbackpacks = true
hybrid-aquatic = true
mushroomquest = true
knightlib = true
offroad = true
naturalist = true
mcwdoors = true
nightlights = true
supplementaries = true
create_vibrant_vaults = true
companions = true
arsdelight = true
create_confectionery = true
adorablehamsterpets = true
minersdelight = true
create = true
culturaldelights = true
aquaculture = true
aeronautics = true
createcasing = true
yungscavebiomes = true
simulated = true
longwings = true
gravestone = true
luminousworld = true
biomeswevegone = true
visualworkbench = true
fungidelight = true
minecraft = true
displaydelight = true
create_dragons_plus = true
rusticdelight = true
createdeco = true
createaddition = true
create_things_and_misc = true
sophisticatedstorage = true
sliceanddice = true
endermanoverhaul = true
aquaculturedelight = true
creeperoverhaul = true
waystones = true
decorative_blocks = true
tradingpost = true
ars_nouveau = true
crabbersdelight = true
sauce = true
create_power_loader = true
