name = "Furber"
author = "faelynjpg"
version = "1.0.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d9e5d21a43c821f09ff852bb8c9bd804be93225c5393b8d60b60a87d708d9b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.235"
